# Science Live Website Configuration - Academic First

base_url = "https://sciencelivehub.github.io"
compile_sass = true
build_search_index = true

title = "Science Live"
description = "Structure what matters. Reuse what works. Collaborate where it counts."
author = "Science Live"

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
subtitle = "Record, Discover, Build & Connect"
footer = "Trusted by science. Powered by nanopublications. Ready for industry."
subdescription = "Science Live helps you to make your work trusted and application-ready."

# Academic-first navigation
main_menu = [
    { name = "For Researchers", url = "#research" },
    { name = "Research Areas", url = "#domains" },
    { name = "Community", url = "https://github.com/ScienceLiveHub/science-live-pipeline/discussions" },
    { name = "Get Started", url = "#start" },
    { name = "For Businesses", url = "#enterprise" }
]

# Academic-focused values
academic_values = [
    {  title = "Discover Faster", description = "Find relevant research across disciplines in minutes, not weeks. Our AI understands scientific concepts and surfaces connections you'd never find through traditional search.", icon = "search"},
    { title = "Connect Globally", description = "Connect with researchers and data scientists tackling similar challenges. Build collaborations across institutions, countries, and disciplines.", icon = "globe"},
    { title = "Structured Knowledge", description = "Structure your data science work into a queryable knowledge base of reusable datasets, models, and code.", icon = "database"},
    { title = "Get Recognition", description = "Receive credit when others build upon your structured contributions. Track your impact beyond traditional citations.", icon = "award"}
]

# Research domains (reframed for academics)
research_domains = [
    { name = "Earth Observation Research", description = "Connect Climate Data with Global Impact", info = "Link satellite observations with ground-truth validation, connect climate models with policy research, and bridge Earth system science with real-world applications.", icon = "satellite", connections = [
            "Remote sensing data ↔ Ground truth validation",
            "Climate models ↔ Observational datasets", 
            "Earth system research ↔ Policy applications",
            "Environmental monitoring ↔ Impact assessment"]},
    { name = "Bioinformatics Research", description = "Bridge Computational Methods with Biological Insights", info = "Accelerate genomic discovery by connecting computational predictions with experimental validation, linking sequence analysis with functional studies.", icon = "dna", connections = [
            "Sequence analysis tools ↔ Functional studies",
            "Omics data ↔ Phenotypic research",
            "Computational predictions ↔ Experimental validation", 
            "Algorithm development ↔ Biological applications" ]},
    { name = "Bio-imaging Research", description = "Connect Imaging Techniques Across Research Scales", info = "Link microscopy methods with quantitative analysis, connect imaging protocols with biological insights, and bridge scales from molecular to tissue-level research.", icon = "microscope", connections = [
            "Microscopy methods ↔ Quantitative analysis",
            "Imaging protocols ↔ Biological insights",
            "Image acquisition ↔ Computational analysis",
            "Method development ↔ Application validation"]},
    { name = "Biodiversity Research", description = "Bridge Species Science with Conservation Impact", info = "Connect taxonomic research with conservation planning, link species data with ecosystem modeling, and bridge biodiversity science with real-world conservation applications.", icon = "leaf", connections = [
            "Species discovery ↔ Conservation planning",
            "Taxonomic data ↔ Ecosystem modeling",
            "Biodiversity monitoring ↔ Habitat management",
            "Climate impacts ↔ Species distribution"]}
]

# metrics title
metrics_enabled = false
metrics_title = "Trusted by Researchers Worldwide"
# Academic-focused metrics
research_metrics = [
    { label = "Structured Research Statements", value = "10,000+" },
    { label = "Active Researchers", value = "2,500+" },
    { label = "Research Institutions", value = "150+" },
    { label = "Faster Research Discovery", value = "5x" }
]

# Academic testimonials
testimonials = [
    { quote = "Science Live helped me discover three key papers I'd never found through traditional search - leading directly to a new collaboration with researchers in Germany.", author = "Dr. Sarah Chen", title = "Climate Scientist, University of California" },
    { quote = "The Zotero plugin transformed my literature review process. What used to take weeks now takes hours, and my structured contributions are already helping other researchers.", author = "Dr. Michael Rodriguez", title = "Computational Biologist, EMBL"},
    { quote = "Finding researchers working on similar imaging problems across different domains has opened up entirely new research directions for our lab.", author = "Prof. Lisa Park", title = "Bio-imaging Specialist, Seoul National University" }
]

# main page button
main_page = {button1 = "Start Free Research Account", button2 = "Enterprise Solutions"}
# Academic-focused CTAs
cta_primary = {title = "Instant Access", description = "Create your free research account and start exploring global knowledge networks in under 2 minutes.", button = "Create Free Account"}
cta_secondary = {title = "Zotero Integration", description = "Install our Zotero plugin and transform your existing bibliography into structured, discoverable knowledge with one click.", button = "Download Plugin"}
cta_tertiary = {title = "Domain Communities", description = "Join active researcher communities in your field to connect with peers and discover relevant work.", button = "Join Community"}
cta_quaternary = {title = "Learn By Examples", description = "Explore curated examples of structured research statements to see how others are making their work discoverable.", button = "View Examples"}

# Academic support contact
contact = { research_support = "mailto:anne.fouilloux@gmail.com", zotero_plugin = "mailto:anne.fouilloux@gmail.com", community = "mailto:anne.fouilloux@gmail.com", enterprise = "mailto:anne.fouilloux@gmail.com"}

# Academic-first brand colors
brand_colors = { primary = "#193967", secondary = "#be2e78", academic_blue = "#0066cc", academic_green = "#28a745"}

# Academic social links
social_links = [
    { name = "GitHub", url = "https://github.com/ScienceLiveHub", icon = "fab fa-github" },
    { name = "Research Community", url = "https://github.com/ScienceLiveHub/science-live-pipeline/discussions", icon = "fas fa-users" }
]

# Enterprise section (minimal)
enterprise = { enabled = true, title = "Trusted by Innovation Leaders", description = "Industry organizations use Science Live to connect their R&D with global research networks", info = "Enterprise research teams accelerate innovation by accessing structured academic knowledge, identifying emerging technologies early, and connecting with research expertise worldwide.", b1= "Institutional-grade security and compliance", b2 = "Custom integrations with research infrastructure", b3 = "Dedicated research support and training", b4 = "Priority access to new research capabilities", b5 = "Connection to global research expertise", b6 = "Accelerated innovation through research networks", cta = "Learn About Enterprise Solutions"}
