# Science Live Website Configuration - Academic First

base_url = "https://sciencelivehub.github.io"
compile_sass = true
build_search_index = true

title = "Science Live"
description = "Turn scattered research into connected, application-ready knowledge."
author = "Science Live"

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"

[extra]
subtitle = "Science Live: Your Research-to-Application Ecosystem"
subdescription = "Built by and for researchers, data scientists, and industry — with full traceability and shared credit."
footer = "Trusted by science. Powered by nanopublications. Ready for industry."

# Academic-first navigation
main_menu = [
    { name = "For Researchers", url = "#academics" },
    { name = "For Data Scientists", url = "#research" },
    { name = "For Industry", url = "#enterprise" },
    { name = "Get Started", url = "#start" },
    { name = "How It Works", url = "#how-it-works" },
]

# Academic-focused values
academic_values = [
    { title = "Publish Structured Findings", description = "Turn your research into traceable nanopublications that automatically track downstream impact and reuse across the innovation chain.", icon = "microscope"},
    { title = "Bridge Research Gaps", description = "Structure data, code, and workflows as nanopubs and earn recognition for critical translation work that makes research application-ready.", icon = "code-branch"},
    { title = "Discover Application-Ready Research", description = "Find research you can actually use with full traceability to data, code, and validation - go from discovery to testing in days, not months.", icon = "industry"},
    { title = "Get Recognition for Impact", description = "Track how your contributions flow through the entire innovation ecosystem, from fundamental research to real-world applications.", icon = "award"}
]

# Research domains (reframed for academics)
research_domains = [
    { name = "Earth Observation Research", description = "Connect Climate Data with Global Impact", info = "Link satellite observations with ground-truth validation, connect climate models with policy research, and bridge Earth system science with real-world applications through the research ecosystem.", icon = "satellite", connections = [
            "Remote sensing data ↔ Ground truth validation",
            "Climate models ↔ Observational datasets", 
            "Earth system research ↔ Policy applications",
            "Environmental monitoring ↔ Impact assessment"]},
    { name = "Bioinformatics Research", description = "Bridge Computational Methods with Biological Insights", info = "Accelerate genomic discovery by connecting computational predictions with experimental validation, linking sequence analysis with functional studies and clinical applications.", icon = "dna", connections = [
            "Sequence analysis tools ↔ Functional studies",
            "Omics data ↔ Phenotypic research",
            "Computational predictions ↔ Experimental validation", 
            "Algorithm development ↔ Biological applications" ]},
    { name = "Bio-imaging Research", description = "Connect Imaging Techniques Across Research Scales", info = "Link microscopy methods with quantitative analysis, connect imaging protocols with biological insights, and bridge scales from molecular to tissue-level research applications.", icon = "microscope", connections = [
            "Microscopy methods ↔ Quantitative analysis",
            "Imaging protocols ↔ Biological insights",
            "Image acquisition ↔ Computational analysis",
            "Method development ↔ Application validation"]},
    { name = "Biodiversity Research", description = "Bridge Species Science with Conservation Impact", info = "Connect taxonomic research with conservation planning, link species data with ecosystem modeling, and bridge biodiversity science with real-world conservation applications.", icon = "leaf", connections = [
            "Species discovery ↔ Conservation planning",
            "Taxonomic data ↔ Ecosystem modeling",
            "Biodiversity monitoring ↔ Habitat management",
            "Climate impacts ↔ Species distribution"]}
]


# Infrastructure
infrastructure = { title = "Built to Last", subtitle = "Connecting researchers, data scientists, and industry with enterprise-grade infrastructure that grows with the global scientific community" , bullet_points = [ {title = "Institutional Partnership", description = "Built in collaboration with Astera Institute with community-driven governance and sustainable funding model, ensuring continued development and long-term platform stability independent of single-source dependencies.", icon = "university"}, {title = "Open Source Foundation", description = "Core platform built on open-source principles with transparent development, ensuring researcher control and community-driven improvements.", icon = "unlock"}, {title = "Enterprise Infrastructure", description = "Reliable, scalable platform infrastructure that handles growing research demands while maintaining fast response times and 99.9% uptime.", icon = "bolt"}, {title = "Growing Network", description = "Join a growing network of structured research statements with active researcher communities across multiple research domains.", icon = "network-wired"} ] } 


# Platform
platform = { title = "The Science Live Ecosystem", subtitle = "Science Live's infrastructure connects research with application across institutions and industries", bullet_points = [ {title = "Decentralized Knowledge Network", description = "Built on nanopublications and distributed servers - no single point of failure, researcher-controlled data"  }, { title = "AI-Powered Discovery Engine", description = "7-step pipeline transforms questions into insights: Query → Intent → Entities → Statements → Results → Answers" }, { title = "Semantic Integration", description = "Standards-based approach (FAIR, RDF, SPARQL) ensures everything connects automatically across domains", terms = "FAIR,RDF,SPARQL" }, { title = "Open Governance", description = "Community-driven development with Astera Institute partnership ensures long-term sustainability and researcher control" } ] } 

# metrics title
metrics_enabled = false
metrics_title = "Building Momentum Toward the Research Ecosystem"
# Academic-focused metrics
# Early engagement metrics (more honest for pre-launch)
research_metrics = [
    { label = "Researchers Expressing Interest", value = "100+" },
    { label = "Target Communities Engaged", value = "4" },
    { label = "Institutional Partnerships", value = "2+" },
    { label = "Expected Launch", value = "Q1 2026" }
]

testimonials = [
    { quote = "Galaxy data scientists create reproducible workflows and publish them on WorkflowHub.eu with workflow reports. Integrating these reports into Science Live's nanopublication network would make our computational workflows discoverable by industry teams while giving data scientists credit for bridging research to application-ready solutions.", author = "Bjoern Gruening, Galaxy Europe Lead", title = "Galaxy Europe Platform" },
    { quote = "Our work on geospatial metadata for scholarly communication - connecting research papers to geographic locations - aligns perfectly with Science Live's structured knowledge approach. There's real potential for collaboration on making research more discoverable through spatial and semantic connections.", author = "Daniel Nüst, TIB Researcher", title = "Technische Informationsbibliothek" },
    { quote = "Having worked with Anne on research software engineering, I'm confident Science Live will solve the fundamental problem of knowledge silos that plague scientific collaboration today.", author = "Research Collaborator", title = "Research Software Engineer" }
]

#research_metrics = [
#    { label = "Research-to-Application Time", value = "6-18 months" },
#    { label = "Translation Contributors", value = "500+" },
#    { label = "Traceable Pathways", value = "1,200+" },
#    { label = "Industry Implementations", value = "50+" }
#]

# Academic testimonials
#testimonials = [
#    { quote = "Science Live helped us validate a climate solution in 8 months instead of 3 years. The full traceability from research to our application gave investors confidence to fund our Series A.", author = "Dr. Maria Santos", title = "CTO, CleanTech Innovations" },
#    { quote = "For the first time, I'm getting cited for the data preparation work that makes research actually usable. My structured contributions have been reused 30+ times across different industries.", author = "Alex Chen", title = "Research Data Scientist, Stanford"},
#    { quote = "My fundamental research on protein folding is now being used in 3 different drug discovery programs. I can track the entire impact chain from my lab to clinical trials.", author = "Prof. James Liu", title = "Biochemistry, University of Toronto" }
#]

# main page button
main_page = {button1 = "Start Publishing Research", url1 = "#start", button2 = "Explore Ecosystem", url2 = "#how-it-works"}
# Academic-focused CTAs
cta_primary = {title = "Instant Access", description = "Create your free research account and start exploring the Science Live global knowledge network in under 2 minutes.", button = "Try it!", button_url = "https://sciencelivehub.github.io/science-live-mockups/"}
cta_secondary = {title = "Zotero Integration", description = "Install our Zotero plugin and transform your existing bibliography into structured, discoverable knowledge with one click.", button = "Download Plugin", button_url = "https://sciencelivehub.github.io/zotero-nanopub-plugin/"}
cta_tertiary = {title = "Learn by Examples", description = "See how your work flows through the entire innovation pipeline from discovery to commercial application.", button = "View Examples & Impact Stories", button_url = "https://sciencelivehub.github.io/science-live-mockups/"}
cta_quaternary = {title = "Science Live Data Pipeline & APIs", description = "Learn, Use and Contribute to our Science Live Data Pipeline and open APIs.", button = "Pipeline Documentation", button_url = "https://sciencelivehub.github.io/science-live-pipeline/index.html"}

# Academic support contact
contact = { research_support = "mailto:anne.fouilloux@gmail.com", zotero_plugin = "mailto:anne.fouilloux@gmail.com", community = "mailto:anne.fouilloux@gmail.com", enterprise = "mailto:anne.fouilloux@gmail.com"}

# Academic-first brand colors
brand_colors = { primary = "#193967", secondary = "#be2e78", academic_blue = "#0066cc", academic_green = "#28a745"}

# Academic social links
social_links = [
    { name = "GitHub", url = "https://github.com/ScienceLiveHub", icon = "fab fa-github" },
    { name = "Research Community", url = "https://github.com/ScienceLiveHub/science-live-pipeline/discussions", icon = "fas fa-users" }
]

# Enterprise section (minimal)
# enterprise = { enabled = true, title = "Accelerate Innovation Through Research Ecosystems", description = "Industry leaders use Science Live to connect R&D with validated academic research and skilled translators", info = "Instead of spending 18 months validating research, find pre-validated work with full traceability to successful applications. Connect directly with researchers and data scientists who can bridge gaps.", b1= "Find application-ready research with validation history", b2 = "Connect with data scientists who bridge research gaps", b3 = "Access full traceability from discovery to implementation", b4 = "Reduce R&D timelines from years to months", b5 = "Build on trusted, peer-validated foundations", b6 = "Track research impact through your innovation pipeline", cta = "Explore Enterprise Ecosystem"}



# Enterprise section (now more clearly for industry)
enterprise = { enabled = true, title = "For Industry: Accelerate R&D with Validated Research", description = "Connect directly with the researchers and data scientists behind breakthrough discoveries", info = "Stop spending 18 months validating academic research. Science Live gives you direct access to pre-validated, application-ready research with full traceability back to original sources and the experts who created them.", b1 = "Find research that's been successfully implemented before", b2 = "Access complete validation history and limitations", b3 = "Connect with the actual researchers for guidance", b4 = "Get implementation-ready code and protocols", b5 = "Track which methods work in production", b6 = "Reduce validation cycles from months to weeks", cta = "Learn More About Enterprise Access"}
