# The URL the site will be built for
base_url = "https://sciencelivehub.github.io"

# The site title and description
title = "Science Live - Transform Research into Living Knowledge"
description = "Science Live revolutionizes how researchers, data scientists, and engineers create, share, and discover knowledge through AI-powered nanopublications and collaborative tools."

# The default language
default_language = "en"

# Theme to use
# theme = "science-live"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

# The taxonomies to be rendered for the site
taxonomies = [
    {name = "categories", paginate_by = 10},
    {name = "tags", paginate_by = 10},
]

# Whether to do syntax highlighting
highlight_code = true

# The theme to use for code highlighting
highlight_theme = "tomorrow-night"

# Whether to generate a feed
generate_feed = true

# The filename to use for the feed
feed_filename = "rss.xml"

# The number of articles to include in the feed
feed_limit = 20

# Configuration of the Markdown rendering
[markdown]
# Whether to do syntax highlighting
highlight_code = true

# Whether external links are to be opened in a new tab
external_links_target_blank = true

# Whether external links are to be no-follow
external_links_no_follow = false

# Whether external links are to be no-referrer
external_links_no_referrer = false

# Whether smart punctuation is enabled
smart_punctuation = true

# Configuration for the search
[search]
# Whether to include the title in the index
include_title = true

# Whether to include the description in the index
include_description = false

# Whether to include the content in the index
include_content = true

# Configuration for the link checker
[link_checker]
# Skip link checking for external URLs
skip_prefixes = [
    "https://",
    "http://",
]

# Various slugification strategies
[slugify]
paths = "safe"
taxonomies = "safe"
anchors = "safe"

[extra]
# Google Analytics
gtm_id = "GTM-WSJ3ZZ29"

# Brand
brand_text = "Science"
brand_live = "Live"
logo_path = "assets/img/network-logo.png"
logo_alt = "Science Live Logo"

# ORCID Button
orcid_button_text = "Sign in with ORCID"

# Author information
author = "Anne Fouilloux"
author_email = "anne.fouilloux@gmail.com"
author_orcid = "0000-0002-1784-2920"

# Social links
github = "https://github.com/sciencelivehub"
twitter = "https://twitter.com/sciencelive"

# Hero Section
hero_title = "Transform Research into Living Knowledge"
hero_subtitle = "Science Live revolutionizes how researchers, data scientists, and engineers create, share, and discover knowledge through AI-powered nanopublications and collaborative tools."
hero_tagline = "Built by and for researchers, data scientists, and industry — with full traceability and shared credit."

# Hero Buttons
hero_primary_button_text = "Get Started"
hero_primary_button_url = "https://sciencelivehub.github.io/science-live-mockups/"
hero_primary_button_icon = "rocket"

hero_secondary_button_text = "Explore Platform"
hero_secondary_button_url = "https://sciencelivehub.github.io/#features"
hero_secondary_button_icon = "compass"

# Hero animation nodes
hero_nodes = ["📄", "🧬", "🔬", "💡", "🌍"]

# Section Headers
features_section_tag = "PLATFORM FEATURES"
features_section_title = "Everything You Need from Modern Research to Scientific Innovation"
features_section_subtitle = "Powerful tools to accelerate innovation across academia and industry"

how_it_works_section_tag = "HOW IT WORKS"
how_it_works_section_title = "Your Knowledge Journey with Science Live"
how_it_works_section_subtitle = "From discovery to deployment in four simple steps"

benefits_section_tag = "BENEFITS"
benefits_section_title = "Why Choose Science Live?"
benefits_section_subtitle = "Join the future of scientific communication and collaboration"

# Benefits Section Content
benefits_main_title = "Accelerate Innovation & Impact"

# CTA Section
cta_title = "Ready to Transform Your Work?"
cta_subtitle = "Join a growing community of researchers, data scientists, and engineers using Science Live to accelerate innovation"

cta_primary_button_text = "Create Free Account"
cta_primary_button_url = "/account"
cta_primary_button_icon = "user-plus"

cta_secondary_button_text = "Read Documentation"
cta_secondary_button_url = "https://sciencelivehub.github.io/science-live-pipeline/"
cta_secondary_button_icon = "book"

# Footer
footer_description = "Trusted by science. Powered by nanopublications. Ready for industry."
footer_copyright_text = "Science Live is an open platform supporting Open Science and collaboration."


# Pricing Configuration
# Move pricing into separate top-level tables to avoid nesting issues

# Pricing global settings
pricing_currency = "€"
pricing_currency_symbol = "€"
pricing_annual_discount_percent = 20
pricing_annual_discount_text = "Save 20%"

# Professional Tier
pricing_professional_monthly = 29
pricing_professional_annual = 23
pricing_professional_research_radar_alerts = 5
pricing_professional_contributor_radar_alerts = 10
pricing_professional_api_calls = 1000

# Team Tier
pricing_team_monthly = 99
pricing_team_annual = 79
pricing_team_users = 5
pricing_team_api_calls = 10000
pricing_team_verifications_included = 5
pricing_team_academic_discount_percent = 50

# Verification Services
pricing_verification_simple_claim = 5
pricing_verification_data = 10
pricing_verification_code = 15
pricing_verification_full_reproduction = 25

# Verification Packages
pricing_verification_starter_count = 10
pricing_verification_starter_price = 80
pricing_verification_standard_count = 50
pricing_verification_standard_price = 350
pricing_verification_unlimited_price = 999

# Credit System
pricing_credit_value = 0.10
pricing_credit_minimum_redemption = 500

# Credit Earnings
[[extra.credit_earnings]]
activity = "Publish nanopublication (claim only)"
credits = 10

[[extra.credit_earnings]]
activity = "Publish with data"
credits = 25

[[extra.credit_earnings]]
activity = "Publish with code/software"
credits = 30

[[extra.credit_earnings]]
activity = "Publish with data + code"
credits = 50

[[extra.credit_earnings]]
activity = "Nanopub gets endorsed (per endorsement)"
credits = 2

[[extra.credit_earnings]]
activity = "Nanopub gets reproduced"
credits = 20

[[extra.credit_earnings]]
activity = "Nanopub gets cited"
credits = 5


# Pricing Tiers
[[extra.pricing_tiers]]
name = "Explorer"
badge = ""
price_monthly = 0
price_text = "forever"
description = "Perfect for individual researchers and contributors"
is_featured = false
cta_text = "Get Started"
cta_url = "https://sciencelivehub.github.io/science-live-mockups/"
cta_style = "secondary"

[[extra.pricing_tiers.features]]
text = "<strong>Unlimited nanopublications</strong>"
included = true

[[extra.pricing_tiers.features]]
text = "Search and discovery"
included = true

[[extra.pricing_tiers.features]]
text = "Earn credits for contributions"
included = true

[[extra.pricing_tiers.features]]
text = "Use credits for verifications"
included = true

[[extra.pricing_tiers.features]]
text = "Earn credit for Community support"
included = true

[[extra.pricing_tiers.features]]
text = "Research Radar alerts"
included = false

[[extra.pricing_tiers.features]]
text = "Contributor Radar alerts"
included = false

[[extra.pricing_tiers.features]]
text = "API access"
included = false

[[extra.pricing_tiers]]
name = "Professional"
badge = "Most Popular"
price_monthly = 0
price_text = "/year"
description = "Unlock Professional by: 10 nanopublications and 5 Science Live Trusted badges"
is_featured = true
cta_text = "Start Contributing"
cta_url = "https://sciencelivehub.github.io/science-live-mockups/"
cta_style = "primary"
unlock_requirements = true

[[extra.pricing_tiers.features]]
text = "Everything in Explorer"
included = true

[[extra.pricing_tiers.features]]
text = "<strong>25 Research Radar alerts</strong>"
included = true

[[extra.pricing_tiers.features]]
text = "<strong>50 Contributor Radar alerts</strong>"
included = true

[[extra.pricing_tiers.features]]
text = "API access (1,000 /month)"
included = true

[[extra.pricing_tiers.features]]
text = "Priority in search results"
included = true

[[extra.pricing_tiers]]
name = "Organisations"
badge = ""
price_annual = 2500
price_text = "/year"
price_suffix = "starting from"
description = "Academic: €2,500 • Government: €3,500 • Commercial: €5,000"
is_featured = false
cta_text = "Contact Sales"
cta_url = "mailto:anne.fouilloux@gmail.com"
cta_style = "secondary"
show_annual_only = true

[[extra.pricing_tiers.features]]
text = "Everything in Professional"
included = true

[[extra.pricing_tiers.features]]
text = "<strong>Unlimited users</strong>"
included = true

[[extra.pricing_tiers.features]]
text = "Team workspace"
included = true

[[extra.pricing_tiers.features]]
text = "Priority support"
included = true

[[extra.pricing_tiers.features]]
text = "API access (10,000 /month)"
included = true

[[extra.pricing_tiers.features]]
text = "Usage analytics"
included = true

# FAQ Items
[[extra.pricing_faq]]
question = "Is contributing really free?"
answer = "Yes! Creating nanopublications, sharing research, and earning credits is completely free. You only pay for advanced monitoring and verification features."

[[extra.pricing_faq]]
question = "What payment methods do you accept?"
answer = "We accept all major credit cards, bank transfers for annual plans, and invoicing for enterprise customers."

[[extra.pricing_faq]]
question = "Can I change plans anytime?"
answer = "Yes, you can upgrade or downgrade your plan at any time. Changes take effect at the next billing cycle."

[[extra.pricing_faq]]
question = "Do you offer academic discounts?"
answer = "Yes! Academic institutions and public research organizations get 50% off Organization plans. Contact us for details."

# Platform statistics
[[extra.hero_stats]]
value = ""
label = ""

[[extra.hero_stats]]
value = ""
label = ""

[[extra.hero_stats]]
value = ""
label = ""

# Navigation menu items
[[extra.nav_links]]
name = "Features"
url = "https://sciencelivehub.github.io/#features"

[[extra.nav_links]]
name = "How It Works"
url = "https://sciencelivehub.github.io/#how-it-works"

[[extra.nav_links]]
name = "Benefits"
url = "https://sciencelivehub.github.io/#benefits"

[[extra.nav_links]]
name = "Pricing"
url = "/pricing"

[[extra.nav_links]]
name = "Documentation"
url = "https://sciencelivehub.github.io/science-live-pipeline/"

# Feature cards
[[extra.features]]
title = "AI Content Generator"
description = "Transform nanopublications—claims, data, software, and workflows—into human-readable formats. Use AI-powered tools to create podcasts, blog posts, executive summaries, and more."
icon = "robot"
icon_type = "fas"
link = "https://sciencelivehub.github.io/science-live-mockups/"
link_text = "Explore Generator"

[[extra.features]]
title = "Research Radar"
description = "Monitor technology maturity across your domains. Track algorithms, datasets, tools, and applications as they progress from concept to production-ready."
icon = "satellite-dish"
icon_type = "fas"
link = "https://sciencelivehub.github.io/science-live-mockups/research-radar"
link_text = "View Research Radar"

[[extra.features]]
title = "Contributor Radar"
description = "Discover experts across academia and industry. Find collaborators based on technical expertise, project experience, and complementary skills."
icon = "network-wired"
icon_type = "fas"
link = "https://sciencelivehub.github.io/science-live-mockups/contributor-radar"
link_text = "Find Collaborators"

[[extra.features]]
title = "Nanopublication Editor"
description = "Create structured, machine-readable claims about your findings, models, and tools. Ensure your innovations are FAIR and properly attributed."
icon = "pen-to-square"
icon_type = "fas"
link = "https://nanodash.knowledgepixels.com/publish"
link_text = "Start Publishing"

[[extra.features]]
title = "Zotero Integration"
description = "Seamlessly convert your reference library into nanopublications. Bridge traditional documentation with modern semantic knowledge graphs."
icon = "book-bookmark"
icon_type = "fas"
link = "https://sciencelivehub.github.io/zotero-nanopub-plugin/"
link_text = "Get Plugin"

[[extra.features]]
title = "Smart Alerts"
description = "Set up custom notifications for breakthroughs in your field. Monitor when research becomes production-ready or when new collaboration opportunities arise."
icon = "bell"
icon_type = "fas"
link = "#"
link_text = "Coming Soon"
coming_soon = true

# Process steps
[[extra.process_steps]]
number = "1"
title = "Create & Publish"
description = "Use our editor or integrations to create nanopublications from your research findings, datasets, models, and software tools."

[[extra.process_steps]]
number = "2"
title = "AI Enhancement"
description = "Let AI transform your technical content into multiple formats, making complex insights accessible to diverse stakeholders."

[[extra.process_steps]]
number = "3"
title = "Monitor & Discover"
description = "Track technology maturity with Research Radar and find experts across academia and industry through Contributor Radar."

[[extra.process_steps]]
number = "4"
title = "Collaborate & Innovate"
description = "Bridge the gap between research and application. Connect with peers, build on shared knowledge, and accelerate innovation."

# Benefits
[[extra.benefits]]
title = "FAIR by Design"
description = "All content follows FAIR principles, ensuring your work is Findable, Accessible, Interoperable, and Reusable across organizations."

[[extra.benefits]]
title = "Cross-Domain Visibility"
description = "AI-powered content generation helps technical insights reach both academic and industry audiences."

[[extra.benefits]]
title = "Technology Tracking"
description = "Monitor how technologies evolve from research concepts to production-ready solutions."

[[extra.benefits]]
title = "Academia-Industry Bridge"
description = "Connect researchers with engineers, data scientists with domain experts, fostering real-world applications."

[[extra.benefits]]
title = "Reproducible Science"
description = "Nanopublications that include data, code, and methods enable true reproducibility."

# Benefit Cards (visual cards on the right)
[[extra.benefit_cards]]
icon = "rocket"
icon_type = "fas"
title = "Increase Innovation Speed"
description = "Teams transfer knowledge faster between research and production."
color = "primary"

[[extra.benefit_cards]]
icon = "globe"
icon_type = "fas"
title = "Industry-Academia Bridge"
description = "Break down silos between academic research and industry applications with unified knowledge sharing."
color = "secondary"

[[extra.benefit_cards]]
icon = "chart-line"
icon_type = "fas"
title = "Measurable ROI"
description = "Track real-world adoption and impact of research outputs across organizations and domains."
color = "success"

# Footer links
[[extra.footer_links]]
text = "Privacy Policy"
url = "/policies"

[[extra.footer_links]]
text = "Terms of Service"
url = "/terms"

# Footer sections
[[extra.footer_sections]]
title = "Platform"
links = [
    {name = "AI Content Generator", url = "https://sciencelivehub.github.io/science-live-mockups/"},
    {name = "Research Radar", url = "https://sciencelivehub.github.io/science-live-mockups/research-radar"},
    {name = "Contributor Radar", url = "https://sciencelivehub.github.io/science-live-mockups/contributor-radar"},
    {name = "Nanopublication Editor", url = "https://nanodash.knowledgepixels.com/publish"},
]

[[extra.footer_sections]]
title = "Resources"
links = [
    {name = "Documentation", url = "https://sciencelivehub.github.io/science-live-pipeline/"},
    {name = "API Reference", url = "https://sciencelivehub.github.io/science-live-pipeline/apidocs/index.html"},
    {name = "GitHub", url = "https://github.com/sciencelivehub"},
]

#[[extra.footer_sections]]
#title = "Community"
#links = [
#    {name = "GitHub", url = "https://github.com/sciencelivehub"},
#    {name = "Discord", url = "#"},
#    {name = "Twitter", url = "#"},
#    {name = "Newsletter", url = "#"},
#]
